---

- name: Checking for virt
  ansible.builtin.command: systemd detect virt
  register: isVirt

- name: Outputting fail message
  ansible.builtin.debug:
    msg: "Not supported on OpenVZ or LXC"
  when: isVirt.stdout == "openvz" or isVirt.stdout == "lxc"

- name: Failing if OpenVZ or LXC
  ansible.builtin.fail:
  when: isVirt.stdout == "openvz" or isVirt.stdout == "lxc"

# Checking for os is not needed here
