---

- name: Installing some needed packages
  ansible.builtin.apt:
    pkg:
      - wireguard
      - iptables
      - resolvconf
      - qrencode
    state: present
    update_cache: true
  become: true

- name: Generating private key
  ansible.builtin.command: wg genkey
  register: server_private_key
  no_log: true

- name: Generating public key
  ansible.builtin.shell: echo "{{ server_private_key.stdout }}" | wg pubkey
  register: server_public_key

- name: Ensuring wireguard directory exists
  ansible.builtin.file:
    path : /etc/wireguard
    state: directory
    mode: '0755'
  become: true

- name: Templating params file
  ansible.builtin.template:
    src: params.j2
    dest: /etc/wireguard/params
    mode: '0700'
  become: true

- name: Templating nic conf file
  ansible.builtin.template:
    src: wg.conf.j2
    dest: /etc/wireguard/{{ server_wg_nic }}.conf
    mode: '0700'
  become: true

- name: Enabling routing on the server
  ansible.builtin.shell: 'echo "net.ipv4.ip_forward = 1" > /etc/sysctl.d/wg.conf'
  become: true

- name: Starting wg service
  ansible.builtin.systemd:
    name: 'wg-quick@{{ server_wg_nic }}'
    state: started
  become: true

- name: Enabling wg service
  ansible.builtin.systemd:
    name: 'wg-quick@{{ server_wg_nic }}'
    enabled: true
    masked: no
  become: true
